### ISSUE TITLE
Re-add generic-array integration

### ISSUE THREAD

**Issue by Seeker14491** [bluss/arrayvec#100]
Integration with the [generic-array](https://crates.io/crates/generic-array/) crate was [added](https://github.com/bluss/arrayvec/pull/41) but then [reverted](https://github.com/bluss/arrayvec/commit/f65ea92da49f7b8cda6ce5df6f7ec85d484046eb) with the following message:

```
- It can be added back later if needed
- A public dependency implies version coupling, and we can't afford to
  have it for a niche use case.
```

It's not clear to me what is meant by the version coupling problem; can we clarify?

**Comment by bluss** [comment]
The plan is to go 1.0 with arrayvec, although as one can notice it's not progressing super fast.
The problem is the "public dependency" problem, and there should be lots of discussion about that on the Rust forums. To state it roughly, Arrayvec 1.0 can only depend on an 1.0 version of generic-array, or equivalent stable version.

**Comment by Seeker14491** [comment]
Perhaps there could be an `unstable` Cargo feature added, which a user would have to opt-in to be able to access this functionality, as described here: https://github.com/rust-lang-nursery/api-guidelines/issues/95

**Comment by bluss** [comment]
With cargo's rename-dependency feature (Rust 1.31), we can have multiple versioned generic-array deps, so this is totally doable now. The problem is that Rust 1.31 is a bit too new a minimum Rust version still, and I don't know if we can conditionally enable this feature.
