### ISSUE TITLE
make ArrayExt public?

### ISSUE THREAD

**Issue by birkenfeld** [bluss/arrayvec#113]
In a library, I need to be generic over arrays, and since I'm anyway depending on `arrayvec` I thought it would make sense to use the `Array` trait for that.

However, the useful `as_slice` method is hidden in the extension trait that's not public. Since it's `unsafe`, it would make sense not to have to duplicate it. Is there a reason not to put that method on `Array` or make the extension trait public?

**Comment by bluss** [comment]
To be correct, the method is only sound on fully initialized arrays and has little use in arrayvec.( Not that we have managed to arrive at fully sound due to missing maybeununit on stable.)

Sure, we can consider making it public and part of the array trait. I'd probably vote no since it has very marginal use - for soundness our design would be better if there were no pointer or slice accessors on arrays directly.

**Comment by birkenfeld** [comment]
I feel like I'm getting mixed messages here, a thumbs up, but "I'd vote no" :smile: ...

**Comment by bluss** [comment]
This is basically happening, the slice methods are moving to the array trait

**Comment by bluss** [comment]
Done in 0.5

**Comment by bluss** [comment]
Note that arrayvec mostly doesn't use the as slice methods itself, except on fully initialized arrays. These are not said to be valid for use on partially initialized arrays, of course (ArrayVec uses a different way to access such values.)
