### ISSUE TITLE
having a TinyVec that fallback to heap

### ISSUE THREAD

**Issue by Stargateur** [bluss/arrayvec#208]
tinyvec have a [`TinyVec`](https://docs.rs/tinyvec/1.5.1/tinyvec/enum.TinyVec.html) that allow to use an array until the size overflow, but the crate require to implement `Default` on the item.

I think the is a nice addition to this crate too but without require the Default implementation.

https://docs.rs/smallvec/1.7.0/smallvec/ fill my request.

**Comment by bluss** [comment]
It sounds out of scope. Smallvec already does this.

**Comment by sffc** [comment]
It would be really convenient if this crate provided heap-overflow versions of ArrayVec and ArrayString.  I would rather not have to carry both `arrayvec` and `smallvec` as code dependencies.  It would be really nice to have a tightly integrated ArrayVec with MaybeArrayVec and ArrayString with MaybeArrayString, for example.

**Comment by bluss** [comment]
Convenience is a very weakly weighing factor unfortunately. Actual gains plus buy-in from smallvec devs could be meaningful here

**Comment by sffc** [comment]
It's not *only* convenience:

1. Every dependency added to our project is heavily scrutinized. (Rather than adding `smallvec` it's more likely that we would use `arrayvec` and roll our own spillover wrapper for it.)
2. There would be more code sharing if `arrayvec` solved both problems.  Code size is a big concern, especially for no_std platforms where `arrayvec` is of particular interest.
